version: '3'
services:
  auth:
    environment:
      - GITHUB_TOKEN
      - DB_URL
      - TEST_CONTAINERS
      - IGNORE_REQUEST_LIMIT
      - NODE_ENV
      - JWT_SECRET_KEY
      - HTTP_PORT=3000
    depends_on: 
      - postgres
    build:
      context: auth/
      args: 
        - GITHUB_TOKEN      
    ports: 
      - "3001:3000" 
  wordlists:
    environment: 
      - TEST_CONTAINERS
      - IGNORE_REQUEST_LIMIT
      - NODE_ENV
      - JWT_SECRET_KEY
      - HTTP_PORT=3000
      - DB_URL
      - GITHUB_TOKEN
    depends_on: 
      - postgres
    build:
      context: wordlists/
      args: 
        - GITHUB_TOKEN
    ports:
    - "3002:3000"
    volumes: 
      - $HOME/.aws/:/root/.aws/:ro
  # quizzes:
  #   environment: 
  #     - TEST_CONTAINERS
  #     - NODE_ENV
  #     - JWT_SECRET_KEY
  #     - DB_URL
  #     - HTTP_PORT=4000
  #     - GITHUB_TOKEN
  #   depends_on: 
  #     - postgres
  #     - auth
  #   build:
  #     context: quizzes/
  #     args: 
  #       - GITHUB_TOKEN      
  #   ports: 
  #     - "3003:4000" 
  youtube:
    environment: 
      - TEST_CONTAINERS
      - NODE_ENV
      - DB_URL
      - SHOW_LOG_ON_STDOUT
      - JWT_SECRET_KEY
      - HTTP_PORT=4000
    depends_on: 
      - postgres
    build:
      context: youtube/
      args: 
        - GITHUB_TOKEN        
    ports: 
      - "3004:4000"      
  postgres:
    environment: 
      - POSTGRES_PASSWORD
      - POSTGRES_DB    
    image: postgres:12-alpine
    ports: 
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes: 
  postgres_data: