version: '3'
services:
  auth:
    depends_on: 
      - db
    build:
      context: auth/
      args:
        JWT_SECRET_KEY: 12345
        MONGO_DB_URL: mongodb://db:27017/decorebator
    ports: 
      - "3000:3000" 
  # wordlists:
  #   build:
  #     context: .
  #     dockerfile: wordlists/Dockerfile
  #     args: 
  #       NODE_ENV: production
  #       JWT_SECRET_KEY: 12345
  #       MONGO_DB_URL: mongodb://db:27017/decorebator
  #       HTTP_PORT: 3000
  #   ports:
  #   - "3000:3000"
  db:
    image: mongo:4.2 
    ports:
      - "27017:27017"
