version: '3'
services:
  auth:
    environment: 
      - TEST_CONTAINERS
      - IGNORE_REQUEST_LIMIT
      - SHOW_LOG_ON_STDOUT
      - NODE_ENV
      - JWT_SECRET_KEY
      - MONGO_DB_URL
      - HTTP_PORT=3000
    depends_on: 
      - db
    build:
      context: auth/
    ports: 
      - "3002:3000" 
  wordlists:
    environment: 
      - TEST_CONTAINERS
      - IGNORE_REQUEST_LIMIT
      - SHOW_LOG_ON_STDOUT
      - NODE_ENV
      - JWT_SECRET_KEY
      - MONGO_DB_URL    
      - HTTP_PORT=3000
    depends_on: 
      - db
    build:
      context: wordlists/
    ports:
    - "3001:3000"
    volumes: 
      - $HOME/.aws/:/root/.aws/:ro
  db:
    image: mongo:4.2 
    ports:
      - "27017:27017"
