version: '3'
services:
  auth:
    environment:
      - DB_URL
      - IGNORE_REQUEST_LIMIT
      - NODE_ENV
      - JWT_SECRET_KEY
      - JWT_EXPIRATION
      - PORT=3000
    depends_on: 
      - postgres
    build:
      context: auth/
    ports: 
      - "3001:3000" 
  wordlists:
    environment: 
      - IGNORE_REQUEST_LIMIT
      - NODE_ENV
      - JWT_SECRET_KEY
      - PORT=3000
      - DB_URL
      - PUB_SUB_WORDS_TOPIC
      - GCLOUD_PROJECT=woven-gist-296814
    depends_on: 
      - postgres
    build:
      context: wordlists/
    ports:
    - "3002:3000"
    volumes:
    - ~/.config/gcloud:/root/.config/gcloud    
  quizzes:
    environment: 
      - NODE_ENV
      - JWT_SECRET_KEY
      - DB_URL
      - PORT=4000
    depends_on: 
      - postgres
    build:
      context: quizzes/
    ports: 
      - "3003:4000" 
  youtube:
    environment: 
      - NODE_ENV
      - DB_URL
      - JWT_SECRET_KEY
      - PORT=4000
    depends_on: 
      - postgres
    build:
      context: youtube/
    ports: 
      - "3004:4000"      
  postgres:
    environment: 
      - POSTGRES_PASSWORD
      - POSTGRES_DB    
    image: postgres:12-alpine
    ports: 
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes: 
  postgres_data: