@crawlerProductionUrl = https://decorebator-crawler-6bzynn6uxa-uc.a.run.app
@crawlerDevUrl = http://localhost:3005

### Auth
curl "https://decorebator-auth-6bzynn6uxa-uc.a.run.app/signin" \
-H "content-type: application/json" \
-d '{"login":"lsimaocosta@gmail.com","password":"123"}'
    


# Use this to create a payload like the pub sub one
# echo '{"languageCode":"en","name":"tear down","id": 12714}' | base64


### Publish 'put through' to oxforddictionaries

curl -d '{"message":{"data":"eyJsYW5ndWFnZUNvZGUiOiJlbiIsIm5hbWUiOiJ0ZWFyIGRvd24iLCJpZCI6IDEyNzI1LCJzb3VyY2UiOiJISVRIRVJfQU5EX1RISVRIRVIifQo="}}' 
    -H "content-type: application/json" 
    http://localhost:3005/words/oxforddictionaries


### Push 'weight in' to news crawler

curl {{crawlerDevUrl}}/words/news -H 'Content-Type: application/json' 
-d'{"message":{"data":"eyJsYW5ndWFnZUNvZGUiOiJlbiIsIm5hbWUiOiJyZW1vdGUiLCJpZCI6IDEyNzI1LCJzb3VyY2UiOiJISVRIRVJfQU5EX1RISVRIRVIifQo="}}'

