@crawlerProductionUrl = https://decorebator-crawler-6bzynn6uxa-uc.a.run.app
@crawlerDevUrl = http://localhost:3005

### Auth
curl "https://decorebator-auth-6bzynn6uxa-uc.a.run.app/signin" \
-H "content-type: application/json" \
-d '{"login":"lsimaocosta@gmail.com","password":"123"}'
    




### Publish 'Luft' to oxforddictionaries

curl -d '{"message":{"data":"eyJsYW5ndWFnZUNvZGUiOiJkZSIsIm5hbWUiOiJsdWZ0IiwiaWQiOiAyMTUyNiwic291cmNlIjoiU1BJRUdFTCJ9Cg=="}}' 
    -H "content-type: application/json" 
    http://localhost:3005/words/oxforddictionaries


# Use this to create a payload like the pub sub one
# echo '{"languageCode":"en","name":"tycoon","id": 21527,"source":"HITHER_AND_THITHER"}' | base64

### Push 'luft' to news crawler



curl {{crawlerDevUrl}}/words/news -H 'Content-Type: application/json' 
-d'{"message":{"data":"eyJsYW5ndWFnZUNvZGUiOiJlcyIsIm5hbWUiOiJjYW1iaW8iLCJpZCI6IDIxNTI3LCJzb3VyY2UiOiJFTF9NVU5ETyJ9Cg=="}}'

